routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('homepage');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/Posts/{id}', 'PostController@userPosts')->name('posts.myPosts');
Route::get('/Posts/delete/{post}', 'PostController@delete')->name('posts.delete');
Route::resource('/posts', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\User;

class Post extends Model
{ 

    protected $table = 'posts';
    protected $fillable = [
      'title','description','isDeleted','user_id',
     ];
    // list All users
    public function All_Posts()
    {
     return $this->all();
    }
    public function All_Posts_desc()
    {
     return $this->orderBy('created_at','desc');
    }
    public function User_Posts_desc($uid)
    {
     return $this->where('user_id',$uid)->orderBy('created_at','desc');
    }
    
    public function user()
    {
        return $this->belongsTo( 'App\User', 'user_id' );
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    protected $table = 'users';
    protected $fillable = [
      'first_name','last_name','username','email',
      'confirm_email','password','role','isDeleted',
     ];
     protected $hidden = [
        'password', 'remember_token',
    ];
  
      public function Uid()
      {
        return Auth::id();
      } 
    
      public function posts()
      {
          return $this->hasMany('App\Post','user_id');
      }
      
     // list All users
     public function users()
     {
      return $this->where([['isDeleted','0'],['role_id','<>','1']])->orderBy('created_at','desc');
     }
    // list of  users has been deleted and list (Desc) by create date
     public function deletedusers()
     {
      return $this->where(['isDeleted','1'],['role_id','<>','1'])->orderBy('updated_at','desc');
     }

    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
   
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use Auth;
use App\User;

use Session;
use Illuminate\Http\Request;
use App\Http\Requests\PostValidation;

class PostController extends Controller
{
    public function index()
    { 
        // get object from POST model 
            $post_model = new Post; 
        /**
         *  call All_Posts_desc Function  in Post Model 
         *  to display all posts with desc created date
         */
            $posts =  $post_model->All_Posts_desc()->get(); 
        
            return view("posts.index",compact("posts"));
        /**   OR
         *  return view("posts.index")->withPosts($posts);
         */
    
    }
    
    public function userPosts($id)
    { 
        $user = User::findOrfail($id);
        // get object from POST model 
            $post_model = new Post; 
        /**
         *  call All_Posts_desc Function  in Post Model 
         *  to display all posts with desc created date
         */
            $posts =  $post_model->User_Posts_desc($user->id)->get(); 
        
            return view("posts.index",compact("posts"));
            /**   OR
             *  return view("posts.index")->withPosts($posts);
             */
        
    }

    public function create()
    {
        return view("posts.create");
    }

    public function store(PostValidation $request)
    {

        $post  = new Post;
        $post->user_id = Auth::id();
        /* First way */
        // $post->title = $request->title;
        // $post->description =$request->description;

        /* OR  Second way */
        $post = $post->fill($request->all());
        
        /* OR  Third way */
        //Post::create($request->all());
        
        $post->save();
        Session::flash('success'," Successfuly created " .$post->title." post");
        return redirect()->route('posts.index');
    }

    
    public function show(Post $post)
    {
        return view("posts.show",compact('post'));
    }

    public function edit(Post $post)
    {
        return view("posts.edit", compact('post'));
    }

   
    public function update(Request $request, Post $post)
    {
        /* First way */
        // $post->title = $request->title;
        // $post->description =$request->description;

        /* OR  Second way */
         $post->update($request->all());    
       
        return redirect()->route('posts.index');
    }
    public function delete(Post $post)
    {
        return view("posts.delete", compact('post'));
    }
    public function destroy(Post $post)
    {   
        $name= $post->title;
        $post = Post::find($post)->first();
        $file->delete();
        Session::flash('success',' Sucessfully deleted the ' .$name . ' post .');
        return redirect()->route('posts.index');
    }
}

resources/views/_includes/forms/account/changepass.blade.php
{{ Form::open(array ('route' => 'post_changePassword', 'method'  => 'POST',
'accept-charset'=>'utf-8','class'  => 'form-horizontal')) }}

<div style="display: none;">
	{{ method_field('POST') }}
	{{ csrf_field() }}
</div>
<legend class="text-center">
	<i class="fa fa-fw fa-key"></i>@lang('lang.change') @lang('lang.password')
</legend>

<div class="row">
	<div class="col-sm-6 col-sm-offset-3">
		<div class="form-group {{ $errors->has('current_password') ? ' has-error' : '' }} required">
				<div class="input-group">
						<span for="current_password" title="current_password"   class="input-group-addon"> 
							<i class="ion ion-android-lock" ></i>
						</span>
				{{ Form::password('current_password', 
					['class' => 'form-control',
					'id' => 'current_password',
					'maxlength'=>'256' ,
					'placeholder'=> Lang::get('lang.old_password')
					,'autofocus']) 
			  }}
		  	</div>
			@if ($errors->has('current_password'))
			<span class="help-block">
				<strong>{{ $errors->first('current_password') }}</strong>
			</span>
			@endif   
		</div> 
	</div>
	<div class="col-sm-6 col-sm-offset-3">
	<div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
			<div class="input-group">
				<span for="password" title="@lang('lang.password')"   class="input-group-addon"> 
					<i class="ion ion-android-unlock" ></i>
				</span>
				<input id="password" type="password" placeholder="@lang('lang.new_password')" class="form-control" name="password" required>
				@if ($errors->has('password'))
				<span class="help-block">
					<strong>{{ $errors->first('password') }}</strong>
				</span>
				@endif

			</div>
		</div>
		<div class="form-group">
			<div class="input-group">
				<span for="password-confirm" title="@lang('lang.password')-confirm"  class="input-group-addon">
					<i class="ion ion-android-unlock" ></i>
				</span>
				<input id="password-confirm" type="password" class="form-control" name="password_confirmation"  placeholder="@lang('lang.confirm_password')" required>

			</div>
		</div>
	</div>
	</div>   
<footer class="text-center bg-light lter">
	{{ Form::submit('Change password',['class' => 'btn btn-success btn-md'])   }}
</footer>
{{ Form::close() }}

resources/views/_includes/forms/account/profile.blade.php
{!! Form::open(array ('route' => 'post_profile', 'method'  => 'POST',
'accept-charset'=>'utf-8','files'  => true)) !!}

<div style="display: none;">
		{{ method_field('POST') }}
		{{ csrf_field() }}
	</div>

<input type="hidden" name="id" value="3">
<legend class="text-center">
	<i class="fa fa-fw fa-file-text-o"></i> 
	@lang('lang.edit')	@lang('lang.profile')
</legend>
<div class="col-sm-12">
		<div class="form-group text {{ $errors->has('avatar') ? ' has-error' : '' }} required">
			{{ Form::label('avatar', Lang::get('lang.profile_image')) }}
			{{ Form::file('avatar',['class' => 'form-control','id' => 'avatar',]) }}
		@if ($errors->has('avatar'))
		<span class="help-block">
			<strong>{{ $errors->first('avatar') }}</strong>
		</span>
		@endif   
	</div> 
<div class="row">
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('first_name') ? ' has-error' : '' }} required">
			{{ Form::label('first_name', 'First Name') }}
			{{ Form::text('first_name',$profile->user->first_name, 
			['class' => 'form-control',
			'id' => 'first_name',
			'maxlength'=>'256' ,
			'placeholder'=>'First Name *'
			]) 
			,'autofocus'
		}}
		@if ($errors->has('first_name'))
		<span class="help-block">
			<strong>{{ $errors->first('first_name') }}</strong>
		</span>
		@endif   
	</div> 
  </div> 
<div class="col-sm-6">
	<div class="form-group text {{ $errors->has('last_name') ? ' has-error' : '' }} required">
		{{ Form::label('last_name', 'Last Name') }}
		{{ Form::text('last_name',$profile->user->last_name,
		[
		'class' => 'form-control',
		'id' => 'last_name',
		'maxlength'=>'256' ,
		'placeholder'=>'Last Name *',
		]) 
		,'autofocus' 
	}}
	@if ($errors->has('last_name'))
	<span class="help-block">
		<strong>{{ $errors->first('last_name') }}</strong>
	</span>
	@endif   
</div>
</div>
<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('username') ? ' has-error' : '' }} required">
			{{ Form::label('username', 'Username') }}
			{{ Form::text('username',$profile->user->username, 
			['class' => 'form-control',
			'id' => 'username',
		    'disabled'=>'true',
			'maxlength'=>'256' ,
			]) 
			,'autofocus'
		}}
		@if ($errors->has('username'))
		<span class="help-block">
			<strong>{{ $errors->first('username') }}</strong>
		</span>
		@endif   
	</div> 
  </div>
<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('email') ? ' has-error' : '' }} required">
			{{ Form::label('email', 'Email') }}
			{{ Form::text('email',$profile->user->email, 
			['class' => 'form-control',
			'id' => 'email',
			'maxlength'=>'256' ,
			'disabled'=>'true',
			]) 
			,'autofocus'
		}}
		@if ($errors->has('email'))
		<span class="help-block">
			<strong>{{ $errors->first('email') }}</strong>
		</span>
		@endif   
	</div> 
  </div> 
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('Address1') ? ' has-error' : '' }} required">
			{{ Form::label('Address1', 'Address 1') }}
			{{ Form::text('Address1',$profile->address->Address1, 
			['class' => 'form-control',
			'id' => 'Address1',
			'maxlength'=>'256' ,
			'placeholder'=>'Address 1'
			]) 
			,'autofocus'
		}}

		@if ($errors->has('Address1'))
		<span class="help-block">
			<strong>{{ $errors->first('Address1') }}</strong>
		</span>
		@endif   
	</div> 
</div> 
<div class="col-sm-6">
	<div class="form-group text {{ $errors->has('Address2') ? ' has-error' : '' }} required">
		{{ Form::label('Address2', 'Address 2') }}
		{{ Form::text('Address2',$profile->address->Address2, 
		['class' => 'form-control',
		'id' => 'Address2',
		'maxlength'=>'256' ,
		'placeholder'=>'Address 2'
		]) 
		,'autofocus'
	}}

	@if ($errors->has('Address2'))
	<span class="help-block">
		<strong>{{ $errors->first('Address2') }}</strong>
	</span>
	@endif   
</div> 
</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('city') ? ' has-error' : '' }} required">
			{{ Form::label('city', 'City') }}
			{{ Form::text('city',$profile->address->city, 
			['class' => 'form-control',
			'id' => 'city',
			'maxlength'=>'256' ,
			'placeholder'=>'City'
			]) 
			,'autofocus'
			}}

		@if ($errors->has('city'))
		<span class="help-block">
			<strong>{{ $errors->first('city') }}</strong>
		</span>
		@endif   
		</div> 
	</div>
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('state') ? ' has-error' : '' }} required">
			{{ Form::label('state', 'State') }}
			{{ Form::text('state',$profile->address->state, 
			['class' => 'form-control',
			'id' => 'state',
			'maxlength'=>'256' ,
			'placeholder'=>'State'
			]) 
			,'autofocus'
				}}

			@if ($errors->has('state'))
			<span class="help-block">
				<strong>{{ $errors->first('state') }}</strong>
			</span>
			@endif   
		</div> 
	</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('zip_code') ? ' has-error' : '' }} required">
			{{ Form::label('zip_code', 'ZIP') }}
			{{ Form::text('zip_code',$profile->address->zip_code, 
			['class' => 'form-control',
			'id' => 'zip_code',
			'maxlength'=>'256' ,
			'placeholder'=>'ZIP'
			]) 
			,'autofocus'
		}}

			@if ($errors->has('zip_code'))
			<span class="help-block">
				<strong>{{ $errors->first('zip_code') }}</strong>
			</span>
			@endif   
		</div> 
	</div>
	@if($countries)
	<div class="col-sm-6">
		<div class="form-group select  {{ $errors->has('country') ? ' has-error' : '' }}  required">
			{!!  Form::label('country', 'Country')   !!}

			{{ Form::select('country', $countries ,$profile->address->country, 
			['class' => "form-control input-sm  $errors->has('country') ? ' has-error' : '' ",'id'=>'country_id'])  }}

				@if ($errors->has('country'))
				<span class="help-block">
					<strong>{{ $errors->first('country') }}</strong>
				</span>
				@endif


			</div> 
		</div>
	@endif 
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group select  {{ $errors->has('withdrawal_method_id') ? ' has-error' : '' }}  required">
			{!!  Form::label('withdrawal_method_id', 'Withdrawal Method')   !!}

			{{ Form::select('withdrawal_method_id', $withdrawMethods ,$profile->withdrawal_method_id, 
			['class' => "form-control input-sm  $errors->has('withdrawal_method_id') ? ' has-error' : '' ",'id'=>'withdrawal_method_id'])  }}

			@if ($errors->has('withdrawal_method_id'))
			<span class="help-block">
				<strong>{{ $errors->first('withdrawal_method_id') }}</strong>
			</span>
			@endif
		</div> 
	</div> 
	<div class="col-sm-6">
		<div class="form-group">
			<div class="form-group text {{ $errors->has('withdrawal_email') ? ' 	has-error' : '' }} required">
				{{ Form::label('withdrawal_email', 'Withdrawal Email') }}
				{{ Form::text('withdrawal_email',$profile->withdrawal_email, 
				['class' => 'form-control',
				'id' => 'withdrawal_email',
				'maxlength'=>'256' ,
				'placeholder'=>'name@email.com',
				'data-required'=>"true"
				]) 
				,'autofocus'
			}}

			@if ($errors->has('withdrawal_email'))
			<span class="help-block">
				<strong>{{ $errors->first('withdrawal_email') }}</strong>
			</span>
			@endif   
		</div> 
		</div>
		</div>
</div>
<div class="row">
	<div class="col-sm-6">
		<div class="form-group text {{ $errors->has('phone_number') ? ' has-error' : '' }} required">
			{{ Form::label('phone_number', 'Phone Number') }}
			{{ Form::text('phone_number',$profile->phone_number, 
			['class' => 'form-control',
			'id' => 'phone_number',
			'placeholder'=>'0123456789'
			]) 
			,'autofocus'
		}}

		@if ($errors->has('phone_number'))
		<span class="help-block">
			<strong>{{ $errors->first('phone_number') }}</strong>
		</span>
		@endif   
	</div> 
</div> 
</div>
<footer class="row footer">
	<hr>
	<center>
		<button class="btn btn-primary btn-md" type="submit">Submit</button>
	</center>
	<hr>
</footer>

{!! Form::close() !!}

<legend class="text-center">Withdrawal Price table</legend>
<div class="col-md-12">
	<table class="table table-bordered table-hover table-striped">
		<tbody>
			<tr>
				<th>Withdrawal Method</th>
				<th>Minimum Withdrawal Amount</th>
			</tr>
			<tr>
				<td>My Wallet</td>
				<td>$5.00</td>
			</tr>
			<tr>
				<td>PayPal</td>
				<td>$1.00</td>
			</tr>
			<tr>
				<td>Payza</td>
				<td>$5.00</td>
			</tr>
			<tr>
				<td>Skrill</td>
				<td>$10.00</td>
			</tr>
			<tr>
				<td>Bitcoin</td>
				<td>$15.00</td>
			</tr>
			<tr>
				<td>Web Money</td>
				<td>$20.00</td>
			</tr>
			<tr>
				<td>Bank Transfer</td>
				<td>$100.00</td>
			</tr>
			<tr>
				<td>FaucetHub</td>
				<td>$10.00</td>
			</tr>
			<tr>
				<td>Payoneer</td>
				<td>$20.00</td>
			</tr>
			<tr>
				<td>Custom Withdrawal Method</td>
				<td>$3.00</td>
			</tr>
		</tbody>
	</table>
</div>
<div class="col-md-10 col-md-offset-1">
<blockquote class="help-block ">
	<p>- For PayPal, Payza, Skrill and Perfect Money add your email.</p>
	<p>- For Bitcoin add your wallet address.</p>
	<p>- For Web Money add your purse.</p>
	<p>- For Payeer add account, e-mail or phone number.</p>
	<p>- For bank transfer add your account holder name, Bank Name, City/Town, Country, Account number, SWIFT, IBAN and Account currency</p>
</blockquote>
</div>

resources/views/_includes/layout_partials/footer.blade.php
<footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
            Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright © 2015 <a href="#">Company</a>.</strong> All rights reserved.
    </footer>

resources/views/_includes/partials/auth.blade.php
@if (Route::has('login'))
    @auth
        @if(Route::is('homepage'))
        <li class="nav-item nav-item-cta last">
            <a class="btn btn-cta btn-cta-secondary" href="{{ url('user/dashboard') }}"> @lang('lang.my_account')
            </a>
        </li>
        @else
        <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                            <span class="thumb-sm avatar pull-left">
                                {{--  @if(Auth::user()->avatar==null)
                                <img src="{{ asset('styles/member/images/avatar.jpg') }}">
                                @else
                                <img src="{{ asset('user/image/Auth::user()->avatar') }}">
                                @endif  --}}
                            </span>
                    {{ Auth::user()->username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <span class="arrow top"></span>
                    <li>
                        <a href="{{route('account.profile')}}">
                                <i class="fa fa-user"> </i>
                                @lang('lang.profile')
                        </a>
                    </li>
                    <li>
                        <a href="{{route('account.changePassword')}}">
                                <i class="fa fa-lock"> </i>
                                @lang('lang.change') @lang('lang.password')
                        </a>
                    </li>
                    <li  class="text-center">
                       <a href="{{ route('logout') }}"
                            onclick="event.preventDefault();
                                        document.getElementById('logout-form').submit();">
                        <b  class="text-danger"> 
                                <i class="fa fa-sign-out"> </i> 
                          @lang('lang.logout')
                        </b>
                        </a>
                      
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                        
                    </li>
                </ul>
            </li>
        @endif
@else
        <li class="nav-item">
            <a href="{{ route('login') }}"> 
            <i class="ion ion-log-in" aria-hidden="true"></i> 
            @lang('lang.login')
            </a>
        </li>
        <li class="nav-item nav-item-cta last">
            <a class="btn btn-cta btn-cta-secondary" href="{{ route('register') }}">
            <i class="ion ion-person-add" aria-hidden="true"></i> 
            @lang('lang.sign_up_free')
            </a>
        </li>
    @endauth
@endif

resources/views/_includes/partials/flash_message.blade.php
@if (session('success'))
    <div class="alert alert-success alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <center> 
            <strong>Success!</strong> {{ session('success') }}
        </center>
     </div>
@endif
@if (session('error'))
<div class="alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <center>  
             <strong>Error!</strong> {{ session('error') }}
        </center>
     </div>
    </div>
@endif

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')
 

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Post </div>

                <div class="card-body">
                    <form method="POST" action="{{ route('posts.store') }}">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-sm-4 col-form-label text-md-right">Title</label>

                            <div class="col-md-6">
                                <input id="title" type="title" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{ old('title') }}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">description</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" name="description" required>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/posts/delete.blade.php
@extends('layouts.app')

@section('content')
 

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header "> {{$post->title}} Post Details </div>
                   <center>
                       <h3> Are You Sur You Want delete this Post </h3>
                   </center>
                    <ul class="unstyled-list">
                    <li>
                        <b class ="text-danger" > Title :    </b> 
                    <i class="text-primary">{{$post->title}} </i>
                    </li>
                    <li>
                        <b class ="text-danger" > Descript :      </b> 
                        <i class="text-primary">{{$post->description}}</i>
                    </li>
                    <li>
                        <b class ="text-danger" > Published By :</b> 
                        <i class="text-primary">{{$post->user->username}}</i>
                    </li>
                    <li><b class ="text-danger" > Created date :   </b> 
                        <i class="text-primary">{{$post->created_at}} </i>
                    </li>
                    <li>
                        <b class ="text-danger" > Updated date :</b> 
                        <i class="text-primary">{{$post->created_at}}    </i>
                    </li>
                   </ul>
                   <form action="{{route('posts.destroy',$post->id)}}" method="PATCH">
                    @csrf   
                    {{ method_field('delete') }} 
                       <div class="modal-footer">
                                <button id="btn-delete" class="btn btn-rounded  pull-right btn-success" type="submit">
                                    <i class="fa fa-trash"></i> @lang('lang.delete')
                                </button>
                          </div>
                    </form>
               </div>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
 

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Post </div>

                <div class="card-body">
                    <form method="PATCH" action="{{ route('posts.store') }}">
                            @csrf
                        <div class="form-group row">
                            <label for="title" class="col-sm-4 col-form-label text-md-right">Title</label>

                            <div class="col-md-6">
                                <input id="title" type="title" class="form-control{{ $errors->has('title') ? ' is-invalid' : '' }}" name="title" value="{{$post->title}}" required autofocus>

                                @if ($errors->has('title'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('title') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="description" class="col-md-4 col-form-label text-md-right">description</label>

                            <div class="col-md-6">
                                <input id="description" type="text" class="form-control{{ $errors->has('description') ? ' is-invalid' : '' }}" value="{{$post->description}}" name="description" required>

                                @if ($errors->has('description'))
                                    <span class="invalid-feedback">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                       

                        <div class="form-group row mb-0">
                            <div class="col-md-8 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    save
                                </button>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>



@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('content')
 

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
            <div class="card-header "> {{$post->title}} Post Details </div>

               <div>
                   <ul class="unstyled-list">
                    <li>
                        <b class ="text-danger" > Title :    </b> 
                    <i class="text-primary">{{$post->title}} </i>
                    </li>
                    <li>
                        <b class ="text-danger" > Descript :      </b> 
                        <i class="text-primary">{{$post->description}}</i>
                    </li>
                    <li>
                        <b class ="text-danger" > Published By :</b> 
                        <i class="text-primary">{{$post->user->username}}</i>
                    </li>
                    <li><b class ="text-danger" > Created date :   </b> 
                        <i class="text-primary">{{$post->created_at}} </i>
                    </li>
                    <li>
                        <b class ="text-danger" > Updated date :</b> 
                        <i class="text-primary">{{$post->created_at}}    </i>
                    </li>
                   </ul>
                   <div class="pull-right">
                    <ul class="list-unstyled list-inline">
                    <li>
                                <a href="{{route('posts.edit',$post->id)}}"  class="btn btn-success">Edit</a>
                    </li>    
                        <li>
                        <form action="{{route('posts.destroy',$post->id)}}" method="post">
                            <button type="submit" class="btn btn-danger">  
                                <i class="fa fa-trash"></i>
                                 @lang('lang.delete')</button>   
                  
                        </form>
                
                        </li>
                    </ul>
                   </div>
               </div>
            </div>
        </div>
    </div>
</div>



@endsection